### ISSUE TITLE
React Native Support

### ISSUE THREAD

**Issue by matthewroche** [standardfile/sfjs#4]
Hi,

I am unable to get this library working with React Native, which the documentation states that it should support. I am using React Native 0.56.0.

Using the documented import process:

`
import { StandardFile } from 'standard-file-js';
let SFJS = new StandardFile();
`

results in the error 'Cannot set property 'SFJS' of undefined'.

Looking at the StandardNotes implementation (https://github.com/standardnotes/mobile/blob/master/src/lib/sfjs.js), it appears that you are required to pass a custom version of Crypto to the standard-file-js library, however this process is not documented. 

When I try to copy the StandardNotes process of creating a custom crypto object, the Aes.pbkdf2() function results in the error "Aes.pbkdf2 was called with 4 arguments but expects 2 arguments" I have tried alternative versions of PBKDF2 but have never been able to sign in successfully.

I think this is a great project, and would love to help encourage adoption. However I feel that either the documentation for this library or the server libraries need updating to better explain the cryto process.

Thanks

**Comment by mobitar** [comment]
Hey @matthewroche, so basically for mobile, we just need to override the basic SFJS methods, because we need to use the native encryption methods on each platform, rather than CryptoJS/WebCrypto, which we use on the web (and is unavailable on mobile). 

We use a fork of [react-native-aes](https://github.com/mobitar/react-native-aes/tree/fb3275f1348db2b01eb385ebd50d7b61dfcf92bb), which define the native encryption methods we need for both iOS and Android. You should first follow the steps there to import it into your project. 

Next, see our implementation for SF within RN: https://github.com/standardnotes/mobile/blob/master/src/lib/sfjs/sfjs.js (updated link after merge).

We create a class called SF which extends StandardFile. The SF requires an instance of crypto. So we give it our SFReactNativeCrypto class, which is defined [in the same file](https://github.com/standardnotes/mobile/blob/master/src/lib/sfjs/sfjs.js#L25). 

Should be about it. Let me know if you've done these steps and are still seeing something different.

**Comment by matthewroche** [comment]
Hi @mobitar 

Your fork was exactly what I needed. Thank you! I'm now able to sign in successfully.

For others who might come accross this, to install the fork directly I used:

`npm i --save git+https://github.com/mobitar/react-native-aes`

Using that package and the functions above results in no errors from pbkdf2 and let me sign in successfully.

@mobitar some gentle feedback from an amateur, but reasonably experienced developer: 

1) The documentation for the models and API at https://standardfile.org/ is good, but the documentation around encryption could use improvement so that those using other languages can more easily follow it.

2) The documentation at https://docs.standardnotes.org/client-development.html is out of date for version 003.

3) RN documentation is none existent. Adding some would probably help drive adoption of the platform. I have had to use source code (and a prod from you). 

I hope to eventually solve some of these problems for others with a more superficial library for react-native. Overall I think your project is great!

**Comment by tectiv3** [comment]
@mobitar don't mind if I take your changes into my fork?

**Comment by mobitar** [comment]
@matthewroche the good news is that the drastic changes have been completed as of version 0.3.0 :) This added the big stuff: authentication, model management, and syncing. So right now all of the Standard Notes production clients no longer use their own custom logic for this, but rely on the shared library. So, I'm definitely confident in its stability. However, documentation still hasn't caught up with the new stuff. Hope to work on this next month.

@tectiv3 of course! It's open source :)
